Repository replicatedhq/ekco, pull requests merged in 2022-10, with the labels that each got.

#70 Add support for rook 1.9
  cmd/ekco/cli/operator.go
  deploy/deployment.yaml
  deploy/serviceaccount.yaml
  go.mod
  go.sum
  pkg/cluster/controller.go
  pkg/cluster/rook_ceph.go
  pkg/cluster/rook_ceph_test.go
  pkg/ekcoops/config.go
  pkg/ekcoops/operator.go
  pkg/logger/logger.go
Labels: type::chore

#71 Upgrade github.com/hashicorp/vault
  go.mod
  go.sum
Labels: type::security

#72 Get rook version from cluster rather than config
  cmd/ekco/cli/init.go
  cmd/ekco/cli/purge_node.go
  pkg/cluster/certs.go
  pkg/cluster/contour_certs.go
  pkg/cluster/controller.go
  pkg/cluster/internallb.go
  pkg/cluster/kotsadm_certs.go
  pkg/cluster/purge_node.go
  pkg/cluster/registry_cert.go
  pkg/cluster/rook_ceph.go
  pkg/cluster/rook_ceph_test.go
  pkg/ekcoops/config.go
  pkg/ekcoops/operator.go
  pkg/util/errors.go
Labels: type::bug, bug::normal

#73 Print rook version in debug log on reconcile
  pkg/ekcoops/operator.go
Labels: type::chore

#75 Enable logging to stdout for haproxy logs
  pkg/internallb/haproxy.cfg
  pkg/internallb/haproxy_test.go
Labels: type::chore

#76 before looking for the rook-ceph operator look for the namespace
  pkg/cluster/rook_ceph.go
  pkg/cluster/rook_ceph_test.go
Labels: type::chore

#77 In order to detect rook, we need to be able to list namespaces
  deploy/serviceaccount.yaml
Labels: type::chore
