Repository replicatedhq/ekco, pull requests merged in 2022-11, with the labels that each got.

#81 Have EKCO manage the scale up of rqlite when 3+ nodes is reached
  go.mod
  pkg/cluster/kotsadm.go
  pkg/cluster/kotsadm_test.go
  pkg/ekcoops/config.go
  pkg/ekcoops/operator.go
Labels: type::feature

#84 Add support for Rook 1.10
  Makefile
  go.mod
  go.sum
  pkg/cluster/constants.go
  pkg/cluster/controller.go
  pkg/cluster/internallb.go
  pkg/cluster/rook_ceph.go
  pkg/cluster/rook_ceph_test.go
  pkg/ekcoops/operator.go
  pkg/ekcoops/prometheus.go
  pkg/k8s/exec.go
  pkg/k8s/mock/mock_exec.go
  pkg/k8s/patch.go
  pkg/webhook/rook-priority.go
Labels: type::chore

#86 Explicitly set replicas to 1
  deploy/deployment.yaml
Labels: type::bug, bug::normal
