Repository replicatedhq/ekco, pull requests merged in 2024-01, with the labels that each got.

#214 bug: diable haproxy zero copy forwarding
  pkg/internallb/haproxy.cfg
  pkg/internallb/haproxy_test.go
Labels: type::bug, bug::regression

#215 ensure that the minio service is enabled after the migration completes
  pkg/cluster/minio.go
  pkg/ekcoops/operator.go
Labels: type::bug, bug::normal

#218 update pvmigrate
  .github/workflows/alpha.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  cmd/ekco/cli/regen-cert.go
  deploy/Dockerfile
  go.mod
  go.sum
  pkg/cluster/kotsadm.go
  pkg/cluster/kotsadm_test.go
  pkg/cluster/registry_cert.go
Labels: type::chore
